dist: xenial
language: python
sudo: false

addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.4

matrix:
  include:
    - python: 3.5
      env: TOXENV=py35-django111
    - python: 3.6
      env: TOXENV=py36-django111
    - python: 3.7
      env: TOXENV=py37-django111
    - python: 3.5
      env: TOXENV=py35-django22
    - python: 3.6
      env: TOXENV=py36-django22
    - python: 3.7
      env: TOXENV=py37-django22
    - python: 3.6
      env: TOXENV=lint

branches:
  only:
    - master

install:
    - pip install tox codecov

before_script:
    - psql -c 'CREATE DATABASE oscar_stores;' -U postgres
    - psql -c 'CREATE EXTENSION postgis;' -U postgres -d oscar_stores
    - psql -c 'CREATE EXTENSION postgis_topology;' -U postgres -d oscar_stores

script:
    - tox

after_success:
  - tox -e coverage-report
  - codecov
