language: python
sudo: false

addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.3

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-django111
    - python: 3.4
      env: TOXENV=py34-django111
    - python: 3.5
      env: TOXENV=py35-django111
    - python: 3.6
      env: TOXENV=py36-django111
    - python: 3.5
      env: TOXENV=py35-django2
    - python: 3.5
      env: TOXENV=py35-django21
    - python: 3.6
      env: TOXENV=py36-django2
    - python: 3.6
      env: TOXENV=py36-django21

    - python: 3.6
      env: TOXENV=lint

install:
    - pip install tox codecov

before_script:
    - psql -c 'CREATE DATABASE oscar_stores;' -U postgres
    - psql -c 'CREATE EXTENSION postgis;' -U postgres -d oscar_stores
    - psql -c 'CREATE EXTENSION postgis_topology;' -U postgres -d oscar_stores

script:
    - tox

after_success:
  - tox -e coverage-report
  - codecov
