language: python
python:
  - 2.7
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq spatialite-bin libspatialite3 libgeos++-dev libgdal-dev libproj0
install:
  - "pip install -r requirements.txt"
  - "python setup.py develop"
script:
  - ./runtests.py
